exec-once = noctalia-shell
exec-once = awww-daemon & udiskie
#exec-once = waybar & nm-applet & mako & makoctl mode -s default $(cat ~/.local/state/theme) & swayosd-server & deezer-desktop --start-in-tray
