$mainMod = SUPER

# -- Hyprland Ecosystem --
# Quit hyprland
bind = $mainMod, M, exit

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
# Move Windows (may be usefull sometimes)
bind = $mainMod, mouse:272, movewindow
bindm = SUPER_SHIFT, mouse:272, resizewindow
bindm = SUPER_SHIFT_ALT, mouse:272, resizewindow 1

# Floating
bind = SUPER_SHIFT, f, exec, ~/scripts/hypr-toggle-floating.sh # togglefloating

# Close programs
bind = $mainMod, C, killactive

# Workspaces
bind = SUPER_SHIFT, left, movetoworkspace, -1
bind = SUPER_SHIFT, right, movetoworkspace, +1

# Screenshot (all screen)
bind = $mainMod, Print, exec, grim ~/Screenshots/$(date +%Y-%m-%d-%H-%M-%S).png
$grimxslurp = grim -g "$(slurp)" ~/Screenshots/$(date +%Y-%m-%d-%H-%M-%S).png
bind = , Print, exec, $grimxslurp 

# -- Open programs --
$ns_prefix = noctalia-shell ipc call
$terminal = kitty
$webBrowser = zen
$fileManager = kitty -e "yazi"
#$menu = wofi --show drun
#$menu = fuzzel
$menu = $ns_prefix launcher toggle
$control_center = $ns_prefix controlCenter toggle 
$session_control = $ns_prefix sessionMenu toggle
$lock_cmd = $ns_prefix lockScreen lock

bind = $mainMod, T, exec, $terminal
bind = $mainMod, W, exec, $webBrowser
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, R, exec, $menu
bind = $mainMod, L, exec, $lock_cmd
bind = SUPER_SHIFT, R, exec, $control_center
bind = CTRL_ALT, DELETE, exec, $session_control #noctalia-shell ipc call sessionMenu toggle


bind = SUPER_SHIFT, T, exec, $ns_prefix darkMode toggle

# Sound
bindel = ,XF86AudioRaiseVolume, exec, $ns_prefix volume increase
bindel = ,XF86AudioLowerVolume, exec, $ns_prefix volume decrease
bindel = ,XF86AudioMute, exec, $ns_prefix volume muteOutput

# Brightness
bindel = ,XF86MonBrightnessUp, exec, $ns_prefix brightness increase
bindel = ,XF86MonBrightnessDown, exec, $ns_prefix brightness decrease
