#windowrule=float, size 50% 50%, center, title:^(Open File|Open Folder)
#windowrule=float, size 1280 720, center, title:^(Steam Settings|Friends List|Paramètres Steam|Liste de contacts|Configuration du contrôleur*)
#windowrule=float, center, class:feh
#windowrule=float, center, class:mpv
#windowrule=float, center, class:nm-connection-editor
#windowrule=float, center, class:blueman-manager

# Kitty
windowrule {
	name = kitty-floating
	match:class = kitty
	center = true
	size = 1280 720
}

# Quand j'ouvre des trucs
windowrule {
	name = floating-centered-open-prompt
	match:title = ^(Open Files|Open Folder|Save File)

	center = true
	float = true
	size = 1280 720
}

# Steam et ses jolies fenetres en +
windowrule {
	name = floating-centered-steam-co
	match:title = ^(Paramètres Steam|Liste de contacts|Configuration du contrôleur*)

	center = true
	float = true
	size = 1280 720
}

# Waydroid
windowrule {
	name = floating-centered-Waydroid
	match:class = ^(Waydroid|Minecraft Launcher)

	center = true
	float = true
	size = 1280 720
}

# Les trucs que je centre
windowrule {
	name = floating-centered-things
	match:class = ^(feh|mpv|nm-connection-editor|blueman-manager)

	center = true
	float = true
}
