# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7b0e0b33-14d6-4c52-b64e-cd99bc14de7b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6E67-C0F1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/games" = {
    device = "/dev/disk/by-uuid/07a6ea2f-dd9c-44a3-aa1e-e509b0c35f99";
    fsType = "ext4";
    options = [ "auto" "nofail" ];
  };

  sops.secrets."credentials" = {
    sopsFile = ../../secrets/smb-Monolith.yaml;
    path = "/etc/smb-secrets";
    mode = "0600";
  };

  fileSystems."/media/Monolith" = {
    device = "//192.168.1.13/kurik";
    fsType = "cifs";
    options = let
      automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,user,users";
      in ["${automount_opts},credentials=/etc/smb-secrets,uid=1001,gid=100"];
  };

  swapDevices = [
    {
      device = "/.swapfile";
      size = 32 * 1024; # 32Go
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
