# Kurikawa's Kitty Configuration

# -- Fonts --
font_family      family="Cascadia Code"
bold_font        auto
italic_font      auto
bold_italic_font auto

# -- Window --
window_padding_width 8

# -- Backgrounds --
#background #061826
background_opacity 0.95
dynamic_background_opacity no

# -- Tab bar appearance --
tab_bar_edge top

tab_title_template "({index}) {title}"
tab_activity_symbol *
tab_bar_style separator
tab_separator " | "

tab_bar_margin_width 0

active_tab_background #EC4067
inactive_tab_foreground #EC4067
inactive_tab_background #061826

# -- Keybinds --

# Reload kitty conf
map ctrl+shift+r load_config_file

# Window management
map ctrl+shift+n new_os_window

# Tab management
# new tab
map ctrl+t new_tab
# close tab
map ctrl+w close_tab
# go to left
map ctrl+alt+left previous_tab
# go to right
map ctrl+alt+right next_tab

# Copy / Paste
copy_on_select no
map ctrl+shift+c copy_to_clipboard

paste_actions replace-dangerous-control-codes
map ctrl+shift+v paste_from_clipboard
