# -------------
#  MAIN CONFIG
# -------------

# Import splitted parts
source=./keybinds.conf
source=./autostart.conf
source=./monitors.conf

# Keyboard
xkb_rules_layout=fr
numlockon=1

# Trackpad

# Mouse

# Layout

circle_layout=monocle,tile
mouse_natural_scrolling = 1
tagrule=id:1,layout_name:monocle
tagrule=id:2,layout_name:tile

# Theming
borderpx = 0;
gappoh = 0;
gappov = 0;
