# -------------
#  MAIN CONFIG
# -------------

# Import splitted parts
source=./keybinds.conf
source=./autostart.conf
source=./monitors.conf
source=../waaaaaagh/appearance.conf

# Mess
syncobj_enable=1

# Keyboard
xkb_rules_layout=fr
numlockon=1

# Trackpad
trackpad_natural_scrolling=1

# Mouse
mouse_natural_scrolling=0

# Layout
circle_layout=monocle,tile
tagrule=id:1,layout_name:monocle
tagrule=id:2,layout_name:tile

# Theming
borderpx = 0;
gappoh = 0;
gappov = 0;

# Monocle top bar
tab_bar_height = 0

# Jump
jump_label_decorate_fg_color=0xc0caf5ff
jump_label_decorate_bg_color=0x1a1b26ff
jump_label_decorate_focus_fg_color=0xc0caf5ff
jump_label_decorate_focus_bg_color=0x1a1b26ff
jump_label_decorate_border_color=0xec4067ff
jump_label_decorate_border_width = 4
jump_label_decorate_corner_radius = 5
jump_label_decorate_padding_x = 10
jump_label_decorate_padding_y = 10
jump_label_decorate_font_desc = Cascadia Mono 24

