# ----------
#  KEYBINDS
# ----------

bind=super+shift,r,reload_config

bind=super,c,killclient

bind=super+shift,tab,switch_layout
bind=super,tab,focusstack,next

bind=super,t,spawn,footclient
bind=super,r,spawn,fuzzel
bind=super,w,spawn,zen
