# ----------
#  KEYBINDS
# ----------

# Reload
bind=super+shift,r,reload_config

# Lock
#bind=super,l,spawn,swaylock
bind=super,l,spawn,noctalia msg session lock

# Kill Client
bind=super,c,killclient

bind=NONE,print,spawn_shell,grim -g "$(slurp)" - | wl-copy
bind=super,print,spawn_shell,grim -t jpeg -q 80 "$(xdg-user-dir SCREENSHOTS)/Screenshot_$(date +'%d.%m.%Y_%H.%M.%S').jpeg"

# Jump
bind=alt, tab, togglejump

# Workspace Navigator
bind=super, left, viewtoleft
bind=super, right, viewtoright
gesturebind=none, left, 3, viewtoleft
gesturebind=none, right, 3, viewtoright

bind = super, 1, view, 1
bind = super, 2, view, 2
bind = super, 3, view, 3
bind = super, 4, view, 4
bind = super, 5, view, 5
bind = super, 6, view, 6
bind = super, 7, view, 7
bind = super, 8, view, 8
bind = super, 9, view, 9

# Layout Control
bind=super+shift,tab,switch_layout
bind=super,tab,focusstack,next
# Move window to other monitors
bind=super+shift,left,tagmon,left
bind=super+shift,right,tagmon,right

# Start some apps
bind=super,t,spawn,footclient
#bind=super,r,spawn,fuzzel
bind=super,r,spawn,noctalia msg panel-toggle launcher
bind=super,w,spawn,zen
bind=super,e,spawn,footclient -e "yazi"

# Volume Control
#bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%+
#bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
#bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute

# Brightness Control
#bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +5%
#bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 5%-
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down

# Media Control
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause