# ----------
#  KEYBINDS
# ----------

# Reload
bind=super+shift,r,reload_config

# Lock
bind=super,l,spawn,swaylock

# Kill Client
bind=super,c,killclient

# Layout Control
bind=super+shift,tab,switch_layout
bind=super,tab,focusstack,next
# Move window to other monitors
bind=super,left,tagmon,left
bind=super,right,tagmon,right

# Start some apps
bind=super,t,spawn,footclient
bind=super,r,spawn,fuzzel
bind=super,w,spawn,zen

# Volume Control
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle

# Brightness Control
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +5%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 5%-

# Media Control
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause
